# .github/contributors.yml
contributors:
  - name: "Manjunath R"
    username: "manju1807"
    profile: "https://github.com/manju1807"
    contributions:
      - "Building the entire application from scratch"
