# .github/support.yml
support:
  issue_template:
    - "Bug Report"
    - "Feature Request"
  contributing:
    link: "https://github.com/manju1807/inventrackpro/docs/contribution-guidelines.md"
    description: "Since I'm the only contributor, feel free to open issues or fork the repo for improvements."
  contact:
    email: "rmanjunath18@outlook.com"
    description: "For inquiries, please email me."
  documentation:
    link: "https://github.com/manju1807/inventrackpro/docs/"
    description: "Visit the documentation for setup and usage instructions."
